import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export const checkStaffRole=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const{data:admin,error:ae}=await context.supabase.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(ae)throw new Error("Não foi possível verificar a função.");if(admin)return true;const{data:editor,error:ee}=await context.supabase.rpc("has_role",{_user_id:context.userId,_role:"editor"});if(ee)throw new Error("Não foi possível verificar a função.");return Boolean(editor)});
export const checkAdminRole=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const{data,error}=await context.supabase.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(error)throw new Error("Não foi possível verificar a função.");return Boolean(data)});
export const inviteEditor=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((data:{email:string})=>data).handler(async({context,data})=>{const{data:ok,error}=await context.supabase.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(error||!ok)throw new Error("Acesso reservado ao administrador.");const{data:inv,error:e}=await supabaseAdmin.auth.admin.inviteUserByEmail(data.email);if(e)throw e;if(inv.user){const{error:re}=await supabaseAdmin.from("user_roles").upsert({user_id:inv.user.id,email:data.email,role:"editor"},{onConflict:"user_id,role"});if(re)throw re}return{ok:true}});
export const removeUserAccess=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).validator((data:{userId:string})=>data).handler(async({context,data})=>{const{data:ok,error}=await context.supabase.rpc("has_role",{_user_id:context.userId,_role:"admin"});if(error||!ok)throw new Error("Acesso reservado ao administrador.");const{error:e}=await supabaseAdmin.from("user_roles").delete().eq("user_id",data.userId).neq("user_id",context.userId);if(e)throw e;return{ok:true}});
export const setupFirstAdmin=createServerFn({method:"POST"}).validator((data:{email:string;password:string})=>data).handler(async({data})=>{const email=data.email.trim().toLowerCase();if(!email||data.password.length<6)throw new Error("Email e palavra-passe válidos são obrigatórios.");const{data:exists,error:ee}=await supabaseAdmin.rpc("admin_exists");if(ee)throw ee;if(exists)throw new Error("A configuração inicial já foi concluída.");const{data:list,error:le}=await supabaseAdmin.auth.admin.listUsers({page:1,perPage:1000});if(le)throw le;const existing=list.users.find(u=>(u.email||"").toLowerCase()===email);if(existing){const{error:ue}=await supabaseAdmin.auth.admin.updateUserById(existing.id,{email_confirm:true});if(ue)throw ue;return{created:false}}const{error:ce}=await supabaseAdmin.auth.admin.createUser({email,password:data.password,email_confirm:true});if(ce)throw ce;return{created:true}});
