import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Search, Star, ArrowUp, X, Minus, Plus } from "lucide-react";
import { useMemo, useState, useEffect } from "react";
import { categoriesQuery, itemsQuery, settingsQuery, signedImageUrl } from "@/lib/menu-queries";
import { formatPrice, normalize } from "@/lib/format";
import { LanguageProvider, getLocalized, pick, useLang } from "@/lib/i18n";
import { CategoryIcons, DividerFlourish, OrnamentalFrame } from "@/lib/menu-visual";
import { OrderCartProvider, useOrderCart } from "@/components/order-cart";

export const Route = createFileRoute("/")({ component: () => <LanguageProvider><PublicMenu /></LanguageProvider> });

function PublicMenu() {
  const { lang, setLang, t } = useLang();
  const categories = useQuery(categoriesQuery());
  const items = useQuery(itemsQuery());
  const settings = useQuery(settingsQuery());
  const [section, setSection] = useState<"restaurante"|"bebidas">("restaurante");
  const [search, setSearch] = useState(""); const [active, setActive] = useState(""); const [top, setTop] = useState(false); const [lightbox, setLightbox] = useState<string|null>(null);
  const visibleCats = useMemo(() => (categories.data ?? []).filter(c => c.section === section), [categories.data, section]);
  const visibleItems = useMemo(() => { const term=normalize(search); return (items.data??[]).filter(i => { const c=(categories.data??[]).find(x=>x.id===i.category_id); if(!c||c.section!==section)return false; return !term || normalize([i.name_pt,i.name_en??"",i.description_pt??"",i.description_en??"",c.name_pt,c.name_en??""].join(" ")).includes(term); }); }, [items.data,categories.data,section,search]);
  const parents=visibleCats.filter(c=>!c.parent_id), children=visibleCats.filter(c=>c.parent_id);
  const catItems=(id:string)=>visibleItems.filter(i=>i.category_id===id); const settingsData=settings.data??{}; const [logoUrl,setLogoUrl]=useState<string|null>(null); useEffect(()=>{let a=true; const p=settingsData['logo_url']; if(!p){setLogoUrl(null);return} if(p.startsWith("http")){setLogoUrl(p);return} signedImageUrl(p).then(u=>{if(a)setLogoUrl(u)}); return()=>{a=false}},[settingsData['logo_url']]);
  useEffect(()=>{const f=()=>setTop(window.scrollY>500);window.addEventListener("scroll",f,{passive:true});return()=>window.removeEventListener("scroll",f)},[]);
  const orderingEnabled = settingsData["ordering_enabled"] === "true";
  const maxItemsPerOrder = Math.max(1, Number(settingsData["max_items_per_order"] || 30));
  return <OrderCartProvider items={items.data ?? []} orderingEnabled={orderingEnabled} maxLines={maxItemsPerOrder}><main className="min-h-screen palm-fade public-menu-motion">
    <header className="border-b border-border/70 bg-background"><div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-4 py-3"><a href="/">{logoUrl?<img src={logoUrl} alt="Villa das Palmeiras" className="h-11 max-w-[190px] object-contain"/>:<span className="font-script text-3xl text-forest">Villa das Palmeiras</span>}</a><div className="flex shrink-0 rounded-full border border-gold/40 bg-cream-deep p-1 text-xs font-semibold"><button className={"rounded-full px-3 py-1 "+(lang==="pt"?"bg-forest text-cream":"text-forest")} onClick={()=>setLang("pt")}>PT</button><button className={"rounded-full px-3 py-1 "+(lang==="en"?"bg-forest text-cream":"text-forest")} onClick={()=>setLang("en")}>EN</button></div></div>
    <div className="mx-auto max-w-3xl px-4 pb-3"><div className="flex rounded-xl border border-border bg-card px-3 py-2 shadow-sm"><Search className="mr-2 mt-0.5 h-4 w-4 text-muted-foreground"/><input aria-label={t("search")} value={search} onChange={e=>setSearch(e.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" placeholder={t("search")}/>{search&&<button onClick={()=>setSearch("")}><X className="h-4 w-4"/></button>}</div></div>
    <DividerFlourish/></header>
    <div className="public-menu-sticky z-40 border-b border-border/70 bg-cream shadow-[0_2px_8px_rgba(27,61,11,0.08)]">
      <div className="mx-auto max-w-3xl">
        <div className="menu-tabs flex border-t border-border/60 px-4 pt-[env(safe-area-inset-top)]">{(["restaurante","bebidas"] as const).map(s=><button key={s} onClick={()=>{setSection(s);setActive("");window.scrollTo({top:0,behavior:"smooth"})}} className={"menu-press flex-1 border-b-2 py-2.5 text-center text-sm font-semibold "+(section===s?"border-gold bg-forest text-cream":"border-gold/70 bg-cream text-forest")}>{s==="restaurante"?t("restaurant"):t("drinks")}</button>)}</div>
        <nav><div className="flex gap-2 overflow-x-auto px-4 py-2 [scrollbar-width:none]">{parents.map(c=><button key={c.id} onClick={()=>{document.getElementById("cat-"+c.id)?.scrollIntoView({behavior:"smooth",block:"start"});setActive(c.id)}} className={"menu-press menu-chip shrink-0 rounded-full border px-3 py-1.5 text-xs font-medium transition-[color,background-color,border-color] duration-150 "+(active===c.id?"menu-chip-active border-gold bg-forest text-cream":"border-border bg-card text-foreground")}>{pick(lang,c.name_pt,c.name_en)}</button>)}</div></nav>
      </div>
    </div>
    {!orderingEnabled&&<div className="mx-auto max-w-3xl px-4 pt-4"><div className="rounded-lg border border-gold/40 bg-gold/10 px-3 py-2 text-center text-xs text-forest">Pedidos pela mesa indisponíveis de momento. Por favor chame o empregado.</div></div>}
    <div key={section} className="menu-section-content mx-auto max-w-3xl px-4 pb-16 pt-5">{(categories.isLoading||items.isLoading)?<MenuSkeleton/>:parents.length===0?<p className="py-16 text-center text-muted-foreground">{t("noResults")}</p>:parents.map(parent=>{const subs=children.filter(c=>c.parent_id===parent.id);return <section id={"cat-"+parent.id} key={parent.id} className="menu-category mb-7"><div className="section-band mb-3 rounded-sm px-4 py-2"><div className="flex items-center justify-center gap-3"><CategoryIcons name={parent.name_pt}/><h2 className="text-2xl font-bold leading-none">{getLocalized(parent.name_pt,parent.name_en,lang)}</h2></div></div><ItemList items={catItems(parent.id)} lang={lang} onImage={setLightbox}/>{subs.map(sub=><div key={sub.id} className="mt-5"><div className="mb-2 flex items-end justify-between border-b border-gold/30 pb-1"><h3 className="font-display text-lg font-semibold text-forest">{getLocalized(sub.name_pt,sub.name_en,lang)}</h3></div><ItemList items={catItems(sub.id)} lang={lang} onImage={setLightbox}/></div>)}</section>})}{visibleItems.length===0&&search&&<p className="py-16 text-center text-muted-foreground">{t("noResults")}</p>}</div>
    <OrnamentalFrame position="footer"><footer className="border-t border-gold/40 bg-forest-deep px-4 py-7 text-center text-sm text-cream/90"><div className="mx-auto max-w-3xl space-y-1"><a href="https://wa.me/258852021633" className="font-semibold text-gold-light">WhatsApp {settingsData['whatsapp']||"+258 85 202 1633"}</a><p>Instagram {settingsData['instagram']||"@grupovilladaspalmeiras"}</p><p>{settingsData['address']||"Katembe-Khaelisa, Maputo"}</p><p>{settingsData['footer_text']||t("prices")}</p></div></footer></OrnamentalFrame>
    {top&&<button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} aria-label={t("top")} title={t("top")} className="menu-press menu-fade fixed bottom-5 right-5 z-50 rounded-full bg-forest p-3 text-cream"><ArrowUp className="h-5 w-5"/></button>}
    {lightbox&&<div className="menu-lightbox fixed inset-0 z-[60] flex items-center justify-center bg-black/80 p-4" onClick={()=>setLightbox(null)}><button className="absolute right-4 top-4 p-2 text-white"><X/></button><img src={lightbox} alt="" className="menu-lightbox-img max-h-[90vh] max-w-full rounded-lg object-contain" onClick={e=>e.stopPropagation()}/></div>}
  </main></OrderCartProvider>;
}
function ItemList({items,lang,onImage}:{items:any[];lang:"pt"|"en";onImage:(url:string)=>void}){return <div>{items.map((i,idx)=><MenuItem key={i.id} item={i} lang={lang} onImage={onImage} index={idx}/>)}</div>}
function MenuItem({item,lang,onImage,index}:{item:any;lang:"pt"|"en";onImage:(url:string)=>void;index:number}){const cart=useOrderCart();const[url,setUrl]=useState<string|null>(item.image_url?.startsWith("http")?item.image_url:null);useEffect(()=>{let a=true;if(item.image_url&&!item.image_url.startsWith("http"))signedImageUrl(item.image_url).then(u=>{if(a)setUrl(u)});return()=>{a=false}},[item.image_url]);return <article className={`menu-press flex gap-3 border-b border-border/60 py-3 last:border-0 ${!item.is_available?"opacity-50":""}`}><button className="shrink-0" disabled={!url} onClick={()=>url&&onImage(url)}><div className="h-16 w-16 overflow-hidden rounded-md bg-muted">{url?<img src={url} loading="lazy" alt="" className="h-full w-full object-cover"/>:null}</div></button><div className="min-w-0 flex-1"><div className="flex items-baseline gap-2"><h3 className="font-semibold">{getLocalized(item.name_pt,item.name_en,lang)}</h3>{item.is_featured&&<Star className="h-3.5 w-3.5 shrink-0 fill-gold text-gold"/>}<span className="dotted-leader"/><span className="shrink-0 font-semibold text-forest">{formatPrice(item.price)}</span>{cart.enabled&&item.is_available&&(cart.quantity(item.id)>0?<span className="ml-1 flex shrink-0 items-center rounded-full border border-gold text-gold"><button type="button" aria-label={lang==="pt"?"Diminuir quantidade":"Decrease quantity"} onClick={()=>cart.decrement(item.id)} className="menu-press flex h-7 w-7 items-center justify-center"><Minus className="h-3.5 w-3.5"/></button><span className="w-6 text-center text-xs font-bold">{cart.quantity(item.id)}</span><button type="button" aria-label={lang==="pt"?"Aumentar quantidade":"Increase quantity"} onClick={()=>cart.add(item.id)} className="menu-press flex h-7 w-7 items-center justify-center"><Plus className="h-3.5 w-3.5"/></button></span>:<button type="button" aria-label={lang==="pt"?"Adicionar ao pedido":"Add to order"} onClick={()=>cart.add(item.id)} className="menu-press ml-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-gold text-gold hover:bg-gold hover:text-cream"><Plus className="h-4 w-4"/></button>)}</div>{getLocalized(item.description_pt,item.description_en,lang)&&<p className="mt-1 text-xs leading-relaxed text-muted-foreground">{getLocalized(item.description_pt,item.description_en,lang)}</p>}{!item.is_available&&<span className="mt-1 inline-block rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold text-muted-foreground">{lang==="pt"?"Esgotado":"Sold out"}</span>}</div></article>}
function MenuSkeleton(){return <div className="space-y-6 animate-pulse">{[1,2,3].map(x=><div key={x}><div className="h-12 rounded-sm bg-muted"/><div className="mt-3 space-y-3">{[1,2,3].map(y=><div key={y} className="h-8 rounded bg-muted"/>)}</div></div>)}</div>}
