import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import QRCode from "qrcode";
import { AdminShell, Field } from "@/components/admin";
import { supabase } from "@/integrations/supabase/client";
import { settingsQuery, signedImageUrl } from "@/lib/menu-queries";

import { toast } from "sonner";
import { tableApi } from "@/lib/tableApi";

export const Route=createFileRoute("/admin/mesas")({component:TablesPage});

function TablesPage(){
  const all=useQuery({queryKey:["restaurant-tables-all"],queryFn:async()=>{const{data,error}=await supabase.from("restaurant_tables").select("*").order("sort_order").order("number");if(error)throw error;return data||[]}}),settings=useQuery(settingsQuery(true)),qc=useQueryClient();
  const [edit,setEdit]=useState<any>(null),[max,setMax]=useState("10");
  const logoPath=settings.data?.["logo_url"];const[logo,setLogo]=useState<string|null>(null);
  useEffect(()=>{if(!logoPath){setLogo(null);return}if(logoPath.startsWith("http")){setLogo(logoPath);return}signedImageUrl(logoPath).then(setLogo)},[logoPath]);
  const save=async()=>{if(!edit?.number?.trim())return;const payload={number:edit.number.trim(),label:edit.label?.trim()||null,is_active:Boolean(edit.is_active),sort_order:Number(edit.sort_order)||0};try{if(edit.id){const{error}=await supabase.from("restaurant_tables").update(payload).eq("id",edit.id);if(error)throw error}else{const{error}=await supabase.from("restaurant_tables").insert(payload);if(error)throw error}toast.success("Mesa guardada.");setEdit(null);qc.invalidateQueries({queryKey:["restaurant-tables"]});qc.invalidateQueries({queryKey:["restaurant-tables-all"]})}catch(e:any){toast.error(e.message)}};
  const createRange=async()=>{const n=Math.max(1,Math.min(200,Number(max)||0));const existing=new Set((all.data||[]).map((x:any)=>String(x.number)));const rows=Array.from({length:n},(_,i)=>({number:String(i+1),is_active:true,sort_order:i})).filter(x=>!existing.has(x.number));if(!rows.length){toast.info("As mesas 1 a "+n+" já existem.");return}const{error}=await supabase.from("restaurant_tables").insert(rows);if(error)toast.error(error.message);else{toast.success(rows.length+" mesas criadas.");qc.invalidateQueries({queryKey:["restaurant-tables"]});qc.invalidateQueries({queryKey:["restaurant-tables-all"]})}};
  return <AdminShell><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold text-forest">Mesas</h1><p className="mt-1 text-sm text-muted-foreground">QR individual por mesa para abrir o menu e fazer pedidos.</p></div><div className="flex gap-2"><input type="number" min="1" max="200" value={max} onChange={e=>setMax(e.target.value)} className="w-24 rounded-lg border px-3 py-2"/><button onClick={createRange} className="rounded-lg bg-forest px-4 py-2 font-semibold text-cream">Criar mesas 1 a N</button><button onClick={()=>window.print()} className="rounded-lg border px-4 py-2">Imprimir folha A4</button></div></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(all.data||[]).map((t:any)=><TableCard key={t.id} table={t} onEdit={setEdit} onRefresh={()=>{qc.invalidateQueries({queryKey:["restaurant-tables"]});qc.invalidateQueries({queryKey:["restaurant-tables-all"]})}}/>)}</div>
  {edit&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-card p-5"><h2 className="text-xl font-bold">{edit.id?"Editar mesa":"Nova mesa"}</h2><div className="mt-4 space-y-3"><Field label="Número"><input value={edit.number} onChange={e=>setEdit({...edit,number:e.target.value})} className="w-full rounded border px-3 py-2"/></Field><Field label="Etiqueta (opcional)"><input value={edit.label||""} onChange={e=>setEdit({...edit,label:e.target.value})} className="w-full rounded border px-3 py-2"/></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={edit.is_active} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/> Activa</label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEdit(null)} className="rounded border px-4 py-2">Cancelar</button><button onClick={save} className="rounded bg-forest px-4 py-2 font-semibold text-cream">Guardar</button></div></div></div>}
  <div id="tables-print-sheet">{logo&&<img src={logo} alt="" className="mx-auto mb-3 h-16 object-contain"/>}<h1>Faça scan para ver o menu e fazer o seu pedido</h1><div className="print-grid">{(all.data||[]).filter((t:any)=>t.is_active).map((t:any)=><PrintableTable key={t.id} table={t}/>)}</div></div>
  <style>{`#tables-print-sheet{display:none}@media print{body *{visibility:hidden!important}#tables-print-sheet,#tables-print-sheet *{visibility:visible!important}#tables-print-sheet{display:block!important;padding:8mm;font-family:Arial,sans-serif;color:#1B3D0B}#tables-print-sheet h1{text-align:center;font-size:18px;margin:0 0 8mm}.print-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8mm}.print-table{break-inside:avoid;text-align:center;border:1px solid #A8732B;padding:5mm}.print-table img{width:38mm;height:38mm;margin:auto}.print-table .number{font-size:28px;font-weight:800;margin-top:2mm}}`}</style>
  </AdminShell>
}
function TableCard({table,onEdit,onRefresh}:{table:any;onEdit:(x:any)=>void;onRefresh:()=>void}){
  const[url,setUrl]=useState(""),[key,setKey]=useState("");
  useEffect(()=>{let alive=true;(async()=>{const{data}=await supabase.from("table_keys").select("access_key").eq("table_id",table.id).maybeSingle();if(alive)setKey(data?.access_key||"")})();return()=>{alive=false}},[table.id]);
  const target=typeof window==="undefined"?"":window.location.origin+"/?mesa="+encodeURIComponent(table.number)+"&k="+encodeURIComponent(key);
  useEffect(()=>{if(key)QRCode.toDataURL(target,{width:600,margin:2,color:{dark:"#1B3D0B",light:"#FBF8F0"}}).then(setUrl)},[target,key]);
  const rotate=async()=>{if(!confirm("Regenerar a chave? Os QR impressos antigos deixam de funcionar."))return;try{const r=await tableApi.rotateTableKey({p_table_id:table.id});if(r?.ok===false||r?.code)throw new Error(String(r.code));const{data}=await supabase.from("table_keys").select("access_key").eq("table_id",table.id).maybeSingle();setKey(data?.access_key||"");toast.success("Chave regenerada.")}catch(e:any){toast.error(e?.message||"Não foi possível regenerar a chave.")}};
  const download=(format:"png"|"svg")=>{if(!key)return;const make=format==="png"?QRCode.toDataURL(target,{width:1600,margin:2,color:{dark:"#1B3D0B",light:"#FBF8F0"}}):QRCode.toString(target,{type:"svg",width:1600,margin:2,color:{dark:"#1B3D0B",light:"#FBF8F0"}});Promise.resolve(make).then(data=>{const href=format==="png"?data:"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(data);const a=document.createElement("a");a.href=href;a.download="mesa-"+table.number+"-qr."+format;a.click()})};
  return <div className={"rounded-xl border bg-card p-4 "+(!table.is_active?"opacity-50":"")}><div className="flex items-center justify-between"><div><div className="text-2xl font-black text-forest">Mesa {table.number}</div>{table.label&&<div className="text-sm text-muted-foreground">{table.label}</div>}</div><span className="text-xs">{table.is_active?"Activa":"Inactiva"}</span></div>{url&&<img src={url} alt={"QR mesa "+table.number} className="mx-auto my-4 h-44 w-44"/>}<div className="flex flex-wrap gap-2"><button disabled={!key} onClick={()=>download("png")} className="rounded border px-3 py-1.5 text-sm">PNG</button><button disabled={!key} onClick={()=>download("svg")} className="rounded border px-3 py-1.5 text-sm">SVG</button><button onClick={rotate} className="rounded border px-3 py-1.5 text-sm">Regenerar chave</button><button onClick={()=>onEdit(table)} className="rounded bg-forest px-3 py-1.5 text-sm font-semibold text-cream">Editar</button></div><p className="mt-2 text-[11px] text-muted-foreground">Os QR impressos antigos deixam de funcionar quando a chave for regenerada.</p></div>}
function PrintableTable({table}:{table:any}){
  const[url,setUrl]=useState("");
  useEffect(()=>{let alive=true;(async()=>{const{data}=await supabase.from("table_keys").select("access_key").eq("table_id",table.id).maybeSingle();if(!alive||!data?.access_key)return;const target=window.location.origin+"/?mesa="+encodeURIComponent(table.number)+"&k="+encodeURIComponent(data.access_key);QRCode.toDataURL(target,{width:800,margin:1,color:{dark:"#1B3D0B",light:"#FBF8F0"}}).then(setUrl)})();return()=>{alive=false}},[table.id,table.number]);
  return <div className="print-table">{url&&<img src={url} alt=""/>}<div className="number">MESA {table.number}</div>{table.label&&<div>{table.label}</div>}</div>
}
