import{ReactNode,useEffect,useState}from"react";import{Link,useNavigate}from"@tanstack/react-router";import{supabase}from"@/integrations/supabase/client";import{checkAdminRole,checkStaffRole}from"@/lib/auth.functions";import{toast}from"sonner";
export function AdminShell({children,adminOnly=false}:{children:ReactNode;adminOnly?:boolean}){const[session,setSession]=useState<any>(undefined);const[allowed,setAllowed]=useState<boolean|null>(null);const[checking,setChecking]=useState(true);const nav=useNavigate();
useEffect(()=>{let alive=true;const resolve=(nextSession:any)=>{if(!alive)return;setSession(nextSession);setAllowed(null);setChecking(true);if(!nextSession){setChecking(false);return}setTimeout(()=>{(adminOnly?checkAdminRole():checkStaffRole()).then(ok=>{if(!alive)return;setAllowed(Boolean(ok));setChecking(false)}).catch(()=>{if(!alive)return;setAllowed(false);setChecking(false)})},0)};
const{data}=supabase.auth.onAuthStateChange((_event,nextSession)=>{setTimeout(()=>resolve(nextSession),0)});supabase.auth.getSession().then(({data:{session:nextSession}})=>resolve(nextSession)).catch(()=>resolve(null));return()=>{alive=false;data.subscription.unsubscribe()}},[adminOnly]);
useEffect(()=>{if(!checking&&session===null)nav({to:"/admin/login",replace:true})},[checking,session,nav]);
if(checking||session===undefined)return<div className="flex min-h-screen items-center justify-center p-5 text-sm text-muted-foreground">A carregar...</div>;
if(session===null)return<div className="flex min-h-screen items-center justify-center p-5 text-sm text-muted-foreground">A redireccionar...</div>;
if(allowed===false)return<div className="flex min-h-screen items-center justify-center p-5"><div className="w-full max-w-md rounded-2xl border bg-card p-6 text-center shadow-sm"><h1 className="text-xl font-bold">Esta conta não tem permissão de administrador</h1><p className="mt-2 text-sm text-muted-foreground">A tua sessão está activa, mas não existe uma função autorizada para esta área.</p><button onClick={async()=>{await supabase.auth.signOut({scope:"local"});setSession(null);setAllowed(null);nav({to:"/admin/login",replace:true})}} className="mt-5 rounded-lg bg-forest px-4 py-2 font-semibold text-cream">Terminar sessão</button></div></div>;
const logout=async()=>{await supabase.auth.signOut({scope:"local"});toast.success("Sessão terminada.");nav({to:"/admin/login",replace:true})};return<div className="min-h-screen bg-background"><header className="sticky top-0 z-40 border-b bg-card/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3"><Link to="/admin" className="font-script text-3xl text-forest">Villa das Palmeiras</Link><button onClick={logout} className="rounded-lg border px-3 py-2 text-sm">Terminar sessão</button></div><nav className="mx-auto flex max-w-6xl gap-1 overflow-x-auto px-4 pb-2 text-sm"><Link to="/admin" className="rounded px-3 py-1.5 hover:bg-muted">Dashboard</Link><Link to="/admin/categorias" className="rounded px-3 py-1.5 hover:bg-muted">Categorias</Link><Link to="/admin/itens" className="rounded px-3 py-1.5 hover:bg-muted">Itens</Link><Link to="/qr" className="rounded px-3 py-1.5 hover:bg-muted">QR code</Link>{adminOnly&&<><Link to="/admin/definicoes" className="rounded px-3 py-1.5 hover:bg-muted">Definições</Link><Link to="/admin/utilizadores" className="rounded px-3 py-1.5 hover:bg-muted">Utilizadores</Link></>}</nav></header><main className="mx-auto max-w-6xl px-4 py-6">{children}</main></div>}
export const Field=({label,children}:{label:string;children:ReactNode})=><label className="block text-sm font-medium">{label}<div className="mt-1">{children}</div></label>;