import { createContext, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Minus, Plus, ShoppingBag, X, CheckCircle2, RefreshCw } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { createOrder, getOrderStatus, type CartLine, type OrderStatus } from "@/lib/orders";
import { tableApi } from "@/lib/tableApi";
import type { Item } from "@/lib/menu-queries";
import { formatPrice } from "@/lib/format";
import { getLocalized, tableErrorMessage, useLang } from "@/lib/i18n";
import { toast } from "sonner";

type OrderCartContextValue={enabled:boolean;add:(itemId:string)=>void;decrement:(itemId:string)=>void;quantity:(itemId:string)=>number;maxLines:number};
const Ctx=createContext<OrderCartContextValue|null>(null);
const fallbackCart:OrderCartContextValue={enabled:false,add:()=>{},decrement:()=>{},quantity:()=>0,maxLines:30};
export const useOrderCart=()=>useContext(Ctx)??fallbackCart;
const tr=(lang:"pt"|"en",pt:string,en:string)=>lang==="en"?en:pt;
const statusLabel=(lang:"pt"|"en",s:OrderStatus)=>({novo:tr(lang,"Recebido","Received"),em_preparacao:tr(lang,"Em preparação","In preparation"),pronto:tr(lang,"Pronto","Ready"),entregue:tr(lang,"Entregue","Delivered"),cancelado:tr(lang,"Cancelado","Cancelled")}[s]);

function storageGet(key:string,local=false){try{return (local?localStorage:sessionStorage).getItem(key)}catch{return null}}
function storageSet(key:string,value:string,local=false){try{(local?localStorage:sessionStorage).setItem(key,value)}catch{}}
function storageRemove(key:string,local=false){try{(local?localStorage:sessionStorage).removeItem(key)}catch{}}

export function OrderCartProvider({children,items,orderingEnabled,maxLines=30}:{children:ReactNode;items:Item[];orderingEnabled:boolean;maxLines?:number}){
  const {lang}=useLang();
  const [cart,setCart]=useState<CartLine[]>([]);
  const [open,setOpen]=useState(false);
  const [customer,setCustomer]=useState("");
  const [customerNote,setCustomerNote]=useState("");
  const [sending,setSending]=useState(false);
  const [sessionToken,setSessionToken]=useState<string|null>(null);
  const [table,setTable]=useState("");
  const [tableKey,setTableKey]=useState("");
  const [tableState,setTableState]=useState<"livre"|"ocupada"|"invalida"|null>(null);
  const [joined,setJoined]=useState(false);
  const [sessionModal,setSessionModal]=useState<"open"|"join"|null>(null);
  const [pin,setPin]=useState("");
  const [pinRepeat,setPinRepeat]=useState("");
  const [attempts,setAttempts]=useState<number|null>(null);
  const [sessionError,setSessionError]=useState<string|null>(null);
  const [confirmation,setConfirmation]=useState<any>(null);
  const [trackedTokens,setTrackedTokens]=useState<string[]>([]);
  const [trackedOrders,setTrackedOrders]=useState<any[]>([]);
  const [sendError,setSendError]=useState(false),[sendErrorCode,setSendErrorCode]=useState(""),[invalidItemIds,setInvalidItemIds]=useState<string[]>([]),[honeypot,setHoneypot]=useState("");
  const [myOrdersOpen,setMyOrdersOpen]=useState(false),[myOrders,setMyOrders]=useState<any>(null);
  const [ending,setEnding]=useState(false);
  const [deviceId]=useState(()=>storageGet("vdp-device-id",true)||crypto.randomUUID?.()||Math.random().toString(36).slice(2));
  const itemMap=useMemo(()=>new Map(items.map(i=>[i.id,i])),[items]);
  const total=cart.reduce((sum,l)=>sum+Number(itemMap.get(l.itemId)?.price||0)*l.quantity,0);
  const count=cart.reduce((sum,l)=>sum+l.quantity,0);

  useEffect(()=>{storageSet("vdp-device-id",deviceId,true)},[deviceId]);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("vdp-order-cart")||"null");if(Array.isArray(saved))setCart(saved);const savedTokens=JSON.parse(localStorage.getItem("vdp-order-tokens")||"[]");if(Array.isArray(savedTokens))setTrackedTokens(savedTokens.filter((x:any)=>typeof x==="string"));const tok=localStorage.getItem("vdp-order-token");if(tok&&!Array.isArray(savedTokens))setTrackedTokens([tok]);const params=new URLSearchParams(window.location.search);const mesa=params.get("mesa");const key=params.get("k");if(mesa&&key){setTable(mesa);setTableKey(key);sessionStorage.setItem("vdp-table-number",mesa);sessionStorage.setItem("vdp-table-key",key);params.delete("k");history.replaceState(null,"",window.location.pathname+(params.toString()?"?"+params.toString():"")+window.location.hash)}else{setTable(sessionStorage.getItem("vdp-table-number")||"");setTableKey(sessionStorage.getItem("vdp-table-key")||"");}const tokSession=localStorage.getItem("vdp-table-token");if(tokSession)setSessionToken(tokSession)}catch{}},[]);
  useEffect(()=>{try{localStorage.setItem("vdp-order-cart",JSON.stringify(cart))}catch{}},[cart]);

  const refreshTable=async()=>{if(!table||!tableKey){setTableState(null);setJoined(false);return}try{const r=await tableApi.getTableState({p_table:table,p_key:tableKey,p_token:sessionToken});if(r?.state==="livre"||r?.state==="ocupada"||r?.state==="invalida"){setTableState(r.state);setJoined(Boolean(r.joined));if(r.joined&&sessionToken)storageSet("vdp-table-token",sessionToken,true);if(r.state==="livre"&&sessionToken){setSessionToken(null);storageRemove("vdp-table-token",true);setJoined(false)}}}catch(e){console.error("get_table_state failed",{message:e instanceof Error?e.message:"unknown"})}};
  useEffect(()=>{void refreshTable();const id=window.setInterval(()=>void refreshTable(),20000);const f=()=>void refreshTable();window.addEventListener("focus",f);return()=>{window.clearInterval(id);window.removeEventListener("focus",f)}},[table,tableKey,sessionToken]);

  const openTable=async()=>{if(pin.length!==4||pin!==pinRepeat){setSessionError(pin.length!==4?tr(lang,"O PIN deve ter 4 dígitos.","PIN must contain 4 digits."):tr(lang,"Os PINs não coincidem.","PINs do not match."));return}setSessionError(null);try{const r=await tableApi.openTable({p_table:table,p_key:tableKey,p_pin:pin,p_device_id:deviceId});setSessionToken(r.token);storageSet("vdp-table-token",r.token,true);setJoined(true);setTableState("ocupada");setSessionModal(null);setPin("");setPinRepeat("");toast.success(tr(lang,"Mesa aberta.","Table opened."))}catch(e:any){setSessionError(e?.code||"E_SERVIDOR")}};
  const joinTable=async()=>{if(pin.length!==4)return;setSessionError(null);try{const r=await tableApi.joinTable({p_table:table,p_key:tableKey,p_pin:pin,p_device_id:deviceId});setSessionToken(r.token);storageSet("vdp-table-token",r.token,true);setJoined(true);setTableState("ocupada");setSessionModal(null);setPin("");setAttempts(null);toast.success(tr(lang,"Entrou na mesa.","Joined table."))}catch(e:any){if(e?.code==="E_PIN")setAttempts(Number(e?.attempts_left??0));setSessionError(e?.code||"E_SERVIDOR")}};
  const endTable=async()=>{if(!sessionToken)return;setEnding(true);try{const r=await tableApi.endTableByClient({p_token:sessionToken});if(r?.ok===false||r?.code)throw new Error(String(r.code));setSessionToken(null);storageRemove("vdp-table-token",true);setJoined(false);setTableState("livre");setCart([]);toast.success(tr(lang,"Mesa encerrada.","Table closed."))}catch(e){toast.error(tr(lang,"Não foi possível encerrar a mesa.","Could not close the table."))}finally{setEnding(false)}};

  useEffect(()=>{if(!trackedTokens.length)return;let alive=true;const poll=async()=>{if(document.visibilityState==="hidden")return;const results=await Promise.all(trackedTokens.map(async t=>{try{return await getOrderStatus(t)}catch(e){console.error("get_order_status failed",{message:e instanceof Error?e.message:"unknown"});return null}}));if(!alive)return;const now=Date.now(),kept:string[]=[],next:any[]=[];results.forEach((d,i)=>{if(!d)return;const terminal=d.status==="entregue"||d.status==="cancelado";const age=now-new Date(d.created_at||now).getTime();if(terminal&&age>2*60*60*1000)return;kept.push(trackedTokens[i]!);next.push({...d,token:trackedTokens[i]})});setTrackedTokens(kept);setTrackedOrders(next);if(next[0])setConfirmation(next.find(x=>x.token===confirmation?.token)||next[0]);try{localStorage.setItem("vdp-order-tokens",JSON.stringify(kept));if(kept[0])localStorage.setItem("vdp-order-token",kept[0]);else localStorage.removeItem("vdp-order-token")}catch{}};void poll();const id=setInterval(poll,8000);const f=()=>{if(document.visibilityState==="visible")void poll()};document.addEventListener("visibilitychange",f);window.addEventListener("focus",f);return()=>{alive=false;clearInterval(id);document.removeEventListener("visibilitychange",f);window.removeEventListener("focus",f)}},[trackedTokens,confirmation?.token]);

  const add=(itemId:string)=>{if(!orderingEnabled)return;if(!joined){setSessionModal(tableState==="livre"?"open":"join");return;}const item=itemMap.get(itemId);if(!item?.is_active||!item.is_available)return;setCart(prev=>{const x=prev.find(v=>v.itemId===itemId);if(x)return prev.map(v=>v.itemId===itemId?{...v,quantity:Math.min(20,v.quantity+1)}:v);if(prev.length>=maxLines){toast.error(tr(lang,"Limite de itens atingido.","Item limit reached."));return prev}return [...prev,{itemId,quantity:1,note:""}]})};
  const decrement=(id:string)=>setCart(prev=>prev.flatMap(x=>x.itemId===id?[{...x,quantity:x.quantity-1}].filter(y=>y.quantity>0):[x]));
  const updateNote=(id:string,note:string)=>setCart(prev=>prev.map(x=>x.itemId===id?{...x,note:note.slice(0,120)}:x));

  const submit=async()=>{if(!orderingEnabled){setSendError(true);setSendErrorCode("E_OFF");return}if(!sessionToken||!joined){setSessionModal(tableState==="livre"?"open":"join");return}if(!cart.length)return;setSending(true);setSendError(false);setSendErrorCode("");setInvalidItemIds([]);try{const result=await createOrder({session_token:sessionToken,device_id:deviceId,items:cart.map(x=>({item_id:x.itemId,quantity:x.quantity,note:x.note||null})),customer_name:customer.trim()||null,customer_note:customerNote.trim()||null,honeypot});setCart([]);setCustomer("");setCustomerNote("");setOpen(false);setTrackedTokens(prev=>[result.public_token,...prev.filter(x=>x!==result.public_token)]);storageSet("vdp-order-token",result.public_token,true);const data=await getOrderStatus(result.public_token).catch(()=>null);setConfirmation(data||{order_number:result.order_number,status:"novo",table_number:table,items:[],created_at:new Date().toISOString()});toast.success(tr(lang,"Pedido recebido.","Order received."))}catch(e:any){const code=e?.code||"E_SERVIDOR";console.error("create_order failed",{code,message:e?.message||"unknown"});setSendError(true);setSendErrorCode(code);setInvalidItemIds(Array.isArray(e?.itemIds)?e.itemIds:[]);toast.error(code==="E_SESSAO"?tr(lang,"A sua mesa foi encerrada. Leia o QR code outra vez.","Your table session has ended. Scan the QR code again."):code==="E_ITEM"?tr(lang,"Algum prato já não está disponível. Reveja o seu pedido.","An item is no longer available. Review your order."):code==="E_OFF"?tr(lang,"Os pedidos pela mesa estão desligados. Por favor chame o empregado.","Table ordering is turned off. Please call a staff member."):code==="E_LIMITE"?tr(lang,"Aguarde um momento e tente de novo. Se continuar, chame o empregado.","Please wait a moment and try again. If it continues, call a staff member."):tr(lang,"Não foi possível enviar. Tente de novo ou chame o empregado.","Could not send. Try again or call a staff member."))}finally{setSending(false)}};

  useEffect(()=>{if(!open&&!sessionModal&&!myOrdersOpen&&!confirmation)return;const prev=document.body.style.overflow;document.body.style.overflow="hidden";const esc=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setSessionModal(null);setMyOrdersOpen(false);}};document.addEventListener("keydown",esc);return()=>{document.body.style.overflow=prev;document.removeEventListener("keydown",esc)}},[open,sessionModal,myOrdersOpen,confirmation]);
  useEffect(()=>{if(!open)return;const vv=window.visualViewport;const u=()=>document.documentElement.style.setProperty("--order-vvh",`${vv?.height||window.innerHeight}px`);u();vv?.addEventListener("resize",u);vv?.addEventListener("scroll",u);return()=>{vv?.removeEventListener("resize",u);vv?.removeEventListener("scroll",u);document.documentElement.style.removeProperty("--order-vvh")}},[open]);

  const errorText=(code:string)=>tableErrorMessage(lang,code,attempts??undefined);

  const value={enabled:orderingEnabled&&joined,add,decrement,quantity:(id:string)=>cart.find(x=>x.itemId===id)?.quantity||0,maxLines};
  const active=trackedOrders.filter(o=>o.status!=="entregue"&&o.status!=="cancelado");
  return <Ctx.Provider value={value}>{children}
    {table&&!joined&&tableState==="livre"&&orderingEnabled&&<button onClick={()=>setSessionModal("open")} className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-gold bg-cream px-4 py-2 text-sm font-semibold text-forest shadow">{tr(lang,`Mesa ${table} · Abrir a sua mesa`,`Table ${table} · Open your table`)}</button>}
    {table&&!joined&&tableState==="ocupada"&&orderingEnabled&&<div className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-gold bg-cream px-4 py-2 text-xs font-semibold text-forest">{tr(lang,"Esta mesa já está aberta. Toque em + e introduza o PIN.","This table is already open. Tap + and enter the PIN.")}</div>}
    {!table&&<div className="mx-auto max-w-3xl px-4 py-3"><div className="rounded-lg border border-gold/40 bg-gold/10 px-3 py-2 text-center text-xs text-forest">{tr(lang,"Para fazer um pedido, leia o QR code da sua mesa.","To place an order, scan your table QR code.")}</div></div>}
    {joined&&table&&<div className="mx-auto flex max-w-3xl items-center justify-between gap-2 px-4 py-2 text-xs"><button onClick={async()=>{const r=await tableApi.getSessionOrders({p_token:sessionToken!});setMyOrders(r);setMyOrdersOpen(true)}} className="rounded-full border border-gold bg-cream px-3 py-1.5 font-semibold text-forest">{tr(lang,`Mesa ${table} · Aberta`,`Table ${table} · Open`)}</button><button disabled={ending} onClick={()=>{if(confirm(tr(lang,"Vai terminar a sessão desta mesa. Já não poderá fazer pedidos e o PIN deixa de funcionar.","This will end this table session. You will no longer be able to order and the PIN will stop working.")))void endTable()}} className="rounded-full border px-3 py-1.5 text-destructive">{tr(lang,"Encerrar mesa","Close table")}</button></div>}
    {active.length>0&&<button onClick={()=>setConfirmation(active[0])} className="fixed bottom-20 left-1/2 z-50 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-xl border border-gold bg-cream px-4 py-2.5 text-sm font-semibold text-forest shadow-md"><span>{tr(lang,"Pedido #","Order #")}{active[0].order_number} · {statusLabel(lang,active[0].status)}</span>{active.length>1&&<span className="text-xs">+{active.length-1}</span>}</button>}
    {orderingEnabled&&joined&&cart.length>0&&<button onClick={()=>setOpen(true)} className="fixed bottom-4 left-1/2 z-50 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-xl border border-gold bg-forest px-4 py-3 text-sm font-semibold text-cream shadow-lg"><span className="flex items-center gap-2"><ShoppingBag className="h-5 w-5 text-gold-light"/>{tr(lang,"Ver pedido","View order")} ({count})</span><span>{formatPrice(total)}</span></button>}

    {(sessionModal||myOrdersOpen||confirmation)&&createPortal(<div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/55 p-2 sm:items-center" onPointerDown={e=>{if(e.target===e.currentTarget){setSessionModal(null);setMyOrdersOpen(false);setConfirmation(null)}}}>
      <div className="flex max-h-[90dvh] w-full max-w-xl flex-col overflow-hidden rounded-2xl border border-gold/30 bg-cream shadow-xl" onPointerDown={e=>e.stopPropagation()}>
        <header className="flex shrink-0 items-center justify-between border-b border-gold/30 px-4 pb-3 pt-[calc(12px+env(safe-area-inset-top))]"><h2 className="text-xl font-bold text-forest">{open?tr(lang,"O meu pedido","My order"):sessionModal==="open"?tr(lang,`Mesa ${table} · Abra a sua mesa`,`Table ${table} · Open your table`):sessionModal==="join"?tr(lang,"Introduza o PIN da mesa","Enter the table PIN"):myOrdersOpen?tr(lang,"Os meus pedidos desta mesa","My orders for this table"):tr(lang,`Pedido #${confirmation?.order_number} · Mesa ${confirmation?.table_number}`,`Order #${confirmation?.order_number} · Table ${confirmation?.table_number}`)}</h2><button onClick={()=>{setSessionModal(null);setMyOrdersOpen(false);setConfirmation(null)}} className="flex h-11 w-11 items-center justify-center rounded-full border border-gold bg-cream text-forest touch-manipulation" aria-label={tr(lang,"Fechar","Close")}><X/></button></header>
        <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-4">
          {sessionModal==="open"&&<div className="space-y-4"><p className="text-sm text-muted-foreground">{tr(lang,"Crie um PIN de 4 dígitos.","Create a 4-digit PIN.")}</p><div className="grid grid-cols-4 gap-2">{[0,1,2,3].map(i=><input key={i} inputMode="numeric" maxLength={1} autoComplete="off" value={pin[i]||""} onChange={e=>setPin((pin.slice(0,i)+e.target.value.replace(/\D/g,"").slice(-1)+pin.slice(i+1)).slice(0,4))} className="h-14 rounded-lg border text-center text-2xl font-bold" aria-label={`PIN ${i+1}`}/>)}</div><p className="text-sm text-muted-foreground">{tr(lang,"Repita o PIN.","Repeat the PIN.")}</p><input inputMode="numeric" maxLength={4} autoComplete="off" value={pinRepeat} onChange={e=>setPinRepeat(e.target.value.replace(/\D/g,"").slice(0,4))} className="w-full rounded-lg border bg-background px-3 py-3 text-center text-2xl tracking-[.5em]"/><p className="text-xs text-muted-foreground">{tr(lang,"Guarde este PIN: as outras pessoas da sua mesa vão precisar dele para pedir.","Keep this PIN: other people at your table will need it to order.")}</p><button onClick={openTable} className="w-full rounded-lg bg-forest px-4 py-3 font-semibold text-cream">{tr(lang,"Abrir mesa","Open table")}</button></div>}
          {open&&<div className="space-y-3">{cart.map(line=>{const item=itemMap.get(line.itemId);if(!item)return null;return <div key={line.itemId} className="rounded-lg border bg-card p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-semibold">{getLocalized(item.name_pt,item.name_en,lang)}</div><div className="text-sm text-forest">{formatPrice(item.price)}</div></div><div className="flex items-center gap-2"><button onClick={()=>decrement(line.itemId)} className="flex h-11 w-11 items-center justify-center rounded-full border touch-manipulation active:scale-95"><Minus className="h-4 w-4"/></button><span className="w-6 text-center font-semibold">{line.quantity}</span><button onClick={()=>add(line.itemId)} className="flex h-11 w-11 items-center justify-center rounded-full border touch-manipulation active:scale-95"><Plus className="h-4 w-4"/></button></div></div><input value={line.note} onChange={e=>updateNote(line.itemId,e.target.value)} maxLength={120} placeholder={tr(lang,"Nota para este item (opcional)","Note for this item (optional)")} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm"/></div>})}</div>}
          {open&&cart.length===0&&<p className="py-10 text-center text-sm text-muted-foreground">{tr(lang,"O seu pedido está vazio.","Your order is empty.")}</p>}
          {sessionModal==="join"&&<div className="space-y-4"><p className="text-sm font-semibold text-forest">{tr(lang,"Esta mesa já está aberta. Introduza o PIN da mesa para fazer pedidos.","This table is already open. Enter the table PIN to place orders.")}</p><input inputMode="numeric" maxLength={4} autoComplete="off" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,4))} className="w-full rounded-lg border bg-background px-3 py-4 text-center text-3xl tracking-[.5em]"/>{attempts!==null&&<p className="text-sm text-muted-foreground">{tr(lang,`Tentativas restantes: ${attempts}`,`Attempts left: ${attempts}`)}</p>}<button onClick={joinTable} className="w-full rounded-lg bg-forest px-4 py-3 font-semibold text-cream">{tr(lang,"Entrar na mesa","Join table")}</button><button onClick={()=>toast.info(tr(lang,"Chame o empregado.","Please call a staff member."))} className="w-full rounded-lg border px-4 py-3">{tr(lang,"Chamar empregado","Call staff")}</button></div>}
          {sessionError&&<div className="mt-3 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{errorText(sessionError)}<div className="mt-1 text-[10px]">Código: {sessionError}</div></div>}
          {myOrdersOpen&&<div className="space-y-3">{(myOrders?.orders||[]).map((o:any)=><div key={o.order_number} className="rounded-lg border bg-card p-3"><div className="flex justify-between font-semibold"><span>#{o.order_number}</span><span>{formatPrice(o.total)}</span></div><div className="mt-2 text-sm">{(o.items||[]).map((x:any,i:number)=><div key={i}>{x.quantity}× {x.name}{x.note&&<span className="text-xs text-muted-foreground"> — {x.note}</span>}</div>)}</div><div className="mt-2 text-xs text-muted-foreground">{statusLabel(lang,o.status)}</div></div>)}<div className="border-t pt-3 text-right font-bold">{tr(lang,"Total da conta","Bill total")}: {formatPrice(Number(myOrders?.total||0))}</div></div>}
          {confirmation&&<div><div className="mb-4">{confirmation.status==="pronto"&&<div className="rounded-lg border border-green-600/30 bg-green-600/10 px-3 py-2 font-semibold text-green-800">{tr(lang,"O seu pedido está pronto!","Your order is ready!")}</div>}{confirmation.status==="cancelado"&&<div className="rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 font-semibold text-destructive">{tr(lang,"O seu pedido foi cancelado. Por favor fale com o empregado.","Your order was cancelled. Please speak to a staff member.")}</div>}</div><div className="grid grid-cols-4 gap-1 text-[10px]">{(["novo","em_preparacao","pronto","entregue"] as OrderStatus[]).map((s,i)=>{const current=["novo","em_preparacao","pronto","entregue"].indexOf(confirmation.status);return <div key={s} className={"rounded px-1 py-2 text-center "+(i<=current?"bg-forest text-cream":"bg-muted text-muted-foreground")}>{statusLabel(lang,s)}</div>})}</div><div className="mt-4 space-y-2">{(confirmation.items||[]).map((x:any,i:number)=><div key={i} className="border-b py-2 text-sm">{x.quantity}× {x.name}</div>)}</div><button onClick={()=>setConfirmation(null)} className="mt-5 w-full rounded-lg bg-forest px-4 py-3 font-semibold text-cream">{tr(lang,"Fazer novo pedido","Place a new order")}</button></div>}
        </div>
        {open&&<footer className="shrink-0 border-t border-gold/30 bg-cream px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3"><div className="flex items-center justify-between text-lg font-bold"><span>Total</span><span className="text-forest">{formatPrice(total)}</span></div>{sendError&&<div className="mt-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{errorText(sendErrorCode)}<div className="text-[10px]">Código: {sendErrorCode||"E_SERVIDOR"}</div></div>}<div className="mt-3 grid gap-2"><label className="text-sm">{tr(lang,"Nome (opcional)","Name (optional)")}<input value={customer} onChange={e=>setCustomer(e.target.value.slice(0,40))} maxLength={40} className="mt-1 w-full rounded border bg-background px-3 py-2"/></label><label className="text-sm">{tr(lang,"Observações (opcional)","Notes (optional)")}<textarea value={customerNote} onChange={e=>setCustomerNote(e.target.value.slice(0,200))} maxLength={200} className="mt-1 min-h-16 w-full rounded border bg-background px-3 py-2"/></label><input value={honeypot} onChange={e=>setHoneypot(e.target.value)} tabIndex={-1} autoComplete="off" aria-hidden className="order-honeypot"/><button disabled={sending||!cart.length||!joined||!orderingEnabled} onClick={submit} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-forest px-4 py-3 font-semibold text-cream disabled:opacity-50">{sending?<><RefreshCw className="h-4 w-4 animate-spin"/>{tr(lang,"A enviar…","Sending…")}</>:tr(lang,"Enviar pedido","Send order")}</button></div></footer>}
      </div>
    </div>,document.body)}
  </Ctx.Provider>;
}
