import { createContext, useContext, useEffect, useMemo, useState, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Minus, Plus, ShoppingBag, X, CheckCircle2 } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { tablesQuery, createOrder, getOrderStatus, type CartLine, type OrderStatus } from "@/lib/orders";
import type { Item } from "@/lib/menu-queries";
import { formatPrice } from "@/lib/format";
import { getLocalized } from "@/lib/i18n";
import { useLang } from "@/lib/i18n";
import { toast } from "sonner";

type OrderCartContextValue = { enabled:boolean; add:(itemId:string)=>void; decrement:(itemId:string)=>void; quantity:(itemId:string)=>number; maxLines:number };
const Ctx=createContext<OrderCartContextValue|null>(null);
const fallbackCart:OrderCartContextValue={enabled:false,add:()=>{},decrement:()=>{},quantity:()=>0,maxLines:30};
export const useOrderCart=()=>useContext(Ctx)??fallbackCart;
function tr(lang:"pt"|"en",pt:string,en:string){return lang==="en"?en:pt}
const statusLabel=(lang:"pt"|"en",s:OrderStatus)=>({novo:tr(lang,"Recebido","Received"),em_preparacao:tr(lang,"Em preparação","In preparation"),pronto:tr(lang,"Pronto","Ready"),entregue:tr(lang,"Entregue","Delivered"),cancelado:tr(lang,"Cancelado","Cancelled")}[s]);

export function OrderCartProvider({children,items,orderingEnabled,maxLines=30}:{children:ReactNode;items:Item[];orderingEnabled:boolean;maxLines?:number}){
  const {lang}=useLang();
  const tables=useQuery(tablesQuery());
  const [cart,setCart]=useState<CartLine[]>([]),[open,setOpen]=useState(false),[table,setTable]=useState(""),[customer,setCustomer]=useState(""),[customerNote,setCustomerNote]=useState(""),[sending,setSending]=useState(false),[token,setToken]=useState<string|null>(null),[confirmation,setConfirmation]=useState<any>(null),[trackedTokens,setTrackedTokens]=useState<string[]>([]),[trackedOrders,setTrackedOrders]=useState<any[]>([]),[sendError,setSendError]=useState(false),[sendErrorCode,setSendErrorCode]=useState<string>(""),[invalidItemIds,setInvalidItemIds]=useState<string[]>([]),[tableError,setTableError]=useState(false),[honeypot,setHoneypot]=useState("");
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("vdp-order-cart")||"null");if(Array.isArray(saved))setCart(saved);const savedToken=localStorage.getItem("vdp-order-token");const savedTokens=JSON.parse(localStorage.getItem("vdp-order-tokens")||"[]");const initialTokens=Array.isArray(savedTokens)?savedTokens.filter((x:any)=>typeof x==="string"):[];if(savedToken&&!initialTokens.includes(savedToken))initialTokens.unshift(savedToken);if(initialTokens.length){setTrackedTokens(initialTokens);setToken(initialTokens[0]);}const savedTable=sessionStorage.getItem("vdp-table-number");const fromUrl=new URLSearchParams(window.location.search).get("mesa");const preferred=fromUrl||savedTable||"";if(preferred){setTable(preferred);sessionStorage.setItem("vdp-table-number",preferred)}}catch{}},[]);
  useEffect(()=>{try{localStorage.setItem("vdp-order-cart",JSON.stringify(cart))}catch{}},[cart]);
  useEffect(()=>{if(!orderingEnabled)return;const preferred=new URLSearchParams(window.location.search).get("mesa");if(preferred&&tables.data?.some(t=>t.number===preferred)){setTable(preferred);try{sessionStorage.setItem("vdp-table-number",preferred)}catch{}}},[orderingEnabled,tables.data]);
  useEffect(()=>{if(!trackedTokens.length)return;let alive=true;
    const poll=async()=>{if(document.visibilityState==="hidden")return;const results=await Promise.all(trackedTokens.map(async t=>{try{return await getOrderStatus(t)}catch(e){console.error("get_order_status failed",e);return null}}));if(!alive)return;
      const now=Date.now();const kept:string[]=[];const next:any[]=[];
      results.forEach((data,idx)=>{if(!data)return;const terminal=data.status==="entregue"||data.status==="cancelado";const age=now-new Date(data.created_at||now).getTime();if(terminal&&age>2*60*60*1000)return;kept.push(trackedTokens[idx]);next.push({...data,token:trackedTokens[idx]});});
      setTrackedTokens(prev=>JSON.stringify(prev)===JSON.stringify(kept)?prev:kept);setTrackedOrders(next);
      const current=next.find(x=>x.token===token);if(current)setConfirmation(current);
      try{localStorage.setItem("vdp-order-tokens",JSON.stringify(kept));if(kept[0])localStorage.setItem("vdp-order-token",kept[0]);else localStorage.removeItem("vdp-order-token")}catch{}
    };
    const resume=()=>{if(document.visibilityState==="visible")void poll()};void poll();const id=window.setInterval(poll,8000);document.addEventListener("visibilitychange",resume);window.addEventListener("focus",resume);return()=>{alive=false;window.clearInterval(id);document.removeEventListener("visibilitychange",resume);window.removeEventListener("focus",resume)};
  },[trackedTokens]);
  useEffect(()=>{const current=trackedOrders.find(o=>o.token===token);if(current)setConfirmation(current)},[trackedOrders,token]);
  const previousStatuses=useRef<Record<string,OrderStatus>>({});
  useEffect(()=>{trackedOrders.forEach(o=>{const prev=previousStatuses.current[o.token];if(o.status==="pronto"&&prev&&prev!=="pronto"&&"vibrate" in navigator){try{navigator.vibrate(180)}catch{}}previousStatuses.current[o.token]=o.status})},[trackedOrders]);
  const itemMap=useMemo(()=>new Map(items.map(i=>[i.id,i])),[items]);
  const total=cart.reduce((sum,l)=>sum+(Number(itemMap.get(l.itemId)?.price||0)*l.quantity),0),count=cart.reduce((sum,l)=>sum+l.quantity,0);
  const add=(itemId:string)=>{if(!orderingEnabled)return;const item=itemMap.get(itemId);if(!item?.is_active||!item.is_available)return;setCart(prev=>{const existing=prev.find(x=>x.itemId===itemId);if(existing)return prev.map(x=>x.itemId===itemId?{...x,quantity:Math.min(20,x.quantity+1)}:x);if(prev.length>=maxLines){toast.error(tr(lang,"Limite de itens atingido.","Item limit reached."));return prev}return [...prev,{itemId,quantity:1,note:""}]})};
  const decrement=(id:string)=>setCart(prev=>prev.flatMap(x=>x.itemId===id?[{...x,quantity:x.quantity-1}].filter(y=>y.quantity>0):[x]));
  const updateNote=(id:string,note:string)=>setCart(prev=>prev.map(x=>x.itemId===id?{...x,note:note.slice(0,120)}:x));
  const submit=async()=>{if(!orderingEnabled){setSendError(true);setSendErrorCode("E_OFF");return}if(!table){setTableError(true);return}if(!cart.length)return;setTableError(false);setSendError(false);setSendErrorCode("");setInvalidItemIds([]);setSending(true);try{const result=await createOrder({table_number:table,items:cart.map(x=>({item_id:x.itemId,quantity:x.quantity,note:x.note||null})),customer_name:customer.trim()||null,customer_note:customerNote.trim()||null,honeypot});setCart([]);setCustomer("");setCustomerNote("");setOpen(false);setToken(result.public_token);setTrackedTokens(prev=>[result.public_token,...prev.filter(x=>x!==result.public_token)]);try{localStorage.removeItem("vdp-order-cart");localStorage.setItem("vdp-order-token",result.public_token)}catch{}const data=await getOrderStatus(result.public_token).catch(()=>null);setConfirmation(data||{order_number:result.order_number,status:"novo",table_number:table,items:[],created_at:new Date().toISOString()});toast.success(tr(lang,"Pedido recebido.","Order received."))}catch(e:any){const code=e?.code||"E_SERVIDOR";console.error("create-order failed",{code,message:e?.message||"unknown"});setSendError(true);setSendErrorCode(code);setInvalidItemIds(Array.isArray(e?.itemIds)?e.itemIds:[]);toast.error(code==="E_MESA"?tr(lang,"Mesa não encontrada. Escolha a sua mesa na lista.","Table not found. Choose your table from the list."):code==="E_ITEM"?tr(lang,"Algum prato já não está disponível. Reveja o seu pedido.","An item is no longer available. Review your order."):code==="E_OFF"?tr(lang,"Os pedidos pela mesa estão desligados. Por favor chame o empregado.","Table ordering is turned off. Please call a staff member."):code==="E_LIMITE"?tr(lang,"Aguarde um momento antes de enviar outro pedido.","Please wait a moment before sending another order."):tr(lang,"Não foi possível enviar. Tente de novo ou chame o empregado.","Could not send. Try again or call a staff member."))}finally{setSending(false)}};
  const newOrder=()=>{setConfirmation(null);setToken(null);setSendError(false);setSendErrorCode("");setInvalidItemIds([]);};
  useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow="hidden";const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("keydown",esc);return()=>{document.body.style.overflow=prev;document.removeEventListener("keydown",esc)}},[open]);
  useEffect(()=>{if(!open)return;const vv=window.visualViewport;const update=()=>document.documentElement.style.setProperty("--order-vvh",`${vv?.height||window.innerHeight}px`);update();vv?.addEventListener("resize",update);vv?.addEventListener("scroll",update);return()=>{vv?.removeEventListener("resize",update);vv?.removeEventListener("scroll",update);document.documentElement.style.removeProperty("--order-vvh")}},[open]);
  const value={enabled:orderingEnabled,add,decrement,quantity:(id:string)=>cart.find(x=>x.itemId===id)?.quantity||0,maxLines};
  return <Ctx.Provider value={value}>{children}
    {trackedOrders.some(o=>o.status!=="entregue"&&o.status!=="cancelado")&&<button onClick={()=>{const o=trackedOrders.find(o=>o.status!=="entregue"&&o.status!=="cancelado")||trackedOrders[0];setToken(o.token);setConfirmation(o)}} className="menu-press fixed bottom-20 left-1/2 z-50 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-xl border border-gold bg-cream px-4 py-2.5 text-sm font-semibold text-forest shadow-md"><span>{tr(lang,"Pedido #","Order #")}{(trackedOrders.find(o=>o.status!=="entregue"&&o.status!=="cancelado")||trackedOrders[0]).order_number} · {statusLabel(lang,(trackedOrders.find(o=>o.status!=="entregue"&&o.status!=="cancelado")||trackedOrders[0]).status)}</span>{trackedOrders.length>1&&<span className="text-xs text-muted-foreground">+{trackedOrders.length-1}</span>}</button>}
    {orderingEnabled&&cart.length>0&&<button onClick={()=>setOpen(true)} className="menu-press fixed bottom-4 left-1/2 z-50 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-xl border border-gold bg-forest px-4 py-3 text-sm font-semibold text-cream shadow-lg"><span className="flex items-center gap-2"><ShoppingBag className="h-5 w-5 text-gold-light"/>{tr(lang,"Ver pedido","View order")} ({count})</span><span>{formatPrice(total)}</span></button>}
    {confirmation&&<div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/50 p-3 sm:items-center"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border bg-cream p-5 shadow-xl"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-forest"><CheckCircle2 className="h-5 w-5"/><h2 className="text-xl font-bold">{tr(lang,"Pedido recebido","Order received")} #{confirmation.order_number}</h2></div><p className="mt-1 text-sm text-muted-foreground">{tr(lang,"Mesa","Table")} {confirmation.table_number}</p></div><button onClick={newOrder} aria-label={tr(lang,"Fechar","Close")}><X/></button></div><div className="mt-4">{trackedOrders.length>1&&<div className="mb-3 flex flex-wrap gap-2">{trackedOrders.map(o=><button key={o.token} onClick={()=>{setToken(o.token);setConfirmation(o)}} className={"rounded-full border px-3 py-1 text-xs "+(confirmation?.token===o.token?"bg-forest text-cream":"bg-card text-forest")}>#{o.order_number} · {statusLabel(lang,o.status)}</button>)}</div>}<div className="mb-3">{confirmation.status==="pronto"&&<div className="rounded-lg border border-gold/50 bg-gold/10 px-3 py-2 text-sm font-semibold text-forest">{tr(lang,"O seu pedido está pronto!","Your order is ready!")}</div>}{confirmation.status==="cancelado"&&<div className="rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm font-semibold text-destructive">{tr(lang,"O seu pedido foi cancelado. Por favor fale com o empregado.","Your order was cancelled. Please speak to a staff member.")}</div>}</div><div className="grid grid-cols-4 gap-1 text-[10px] sm:text-xs">{(["novo","em_preparacao","pronto","entregue"] as OrderStatus[]).map((s,idx)=>{const states=["novo","em_preparacao","pronto","entregue"];const current=states.indexOf(confirmation.status);return <div key={s} className={"rounded px-1 py-2 text-center "+(idx<=current?"bg-forest text-cream":"bg-muted text-muted-foreground")}>{statusLabel(lang,s)}</div>})}</div><div className="mt-5 space-y-2">{(confirmation.items||[]).map((x:any,i:number)=><div key={i} className="flex justify-between border-b border-border/60 py-2 text-sm"><span>{x.quantity}× {getLocalized((items.find(i=>i.name_pt===x.name)?.name_pt)||x.name,(items.find(i=>i.name_pt===x.name)?.name_en)||null,lang)}</span></div>)}</div><button onClick={newOrder} className="mt-5 w-full rounded-lg bg-forest px-4 py-3 font-semibold text-cream">{tr(lang,"Fazer novo pedido","Place a new order")}</button></div></div></div>}
    {open&&createPortal(<div className="order-modal fixed inset-0 z-[100] flex items-end justify-center bg-black/50 p-2 sm:items-center" onPointerDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div role="dialog" aria-modal="true" className="order-modal-panel flex w-full max-w-xl flex-col overflow-hidden rounded-t-2xl border bg-cream shadow-xl sm:rounded-2xl" onPointerDown={e=>e.stopPropagation()}>
      <header className="order-modal-header flex shrink-0 items-center justify-between border-b border-gold/30 px-4 pb-3 pt-[calc(12px+env(safe-area-inset-top))]"><h2 className="text-2xl font-bold text-forest">{tr(lang,"O meu pedido","My order")}</h2><button onClick={()=>setOpen(false)} aria-label={tr(lang,"Fechar","Close")} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-gold bg-cream text-forest touch-manipulation active:scale-95"><X className="h-5 w-5"/></button></header>
      <div className="order-modal-scroll min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-4">
        {sendError&&<div className="mb-3 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">{sendErrorCode==="E_MESA"?tr(lang,"Mesa não encontrada. Escolha a sua mesa na lista.","Table not found. Choose your table from the list."):sendErrorCode==="E_ITEM"?tr(lang,"Algum prato já não está disponível. Reveja o seu pedido.","An item is no longer available. Review your order."):sendErrorCode==="E_OFF"?tr(lang,"Os pedidos pela mesa estão desligados. Por favor chame o empregado.","Table ordering is turned off. Please call a staff member."):sendErrorCode==="E_LIMITE"?tr(lang,"Aguarde um momento antes de enviar outro pedido.","Please wait a moment before sending another order."):<><div>{tr(lang,"Não foi possível enviar. Tente de novo ou chame o empregado.","Could not send. Try again or call a staff member.")}</div><div className="mt-1 text-[10px] opacity-80">Código: {sendErrorCode||"E_SERVIDOR"}</div></>}</div>}
        {tableError&&!table&&<div className="mb-3 rounded-lg border-2 border-gold bg-gold/10 px-3 py-3 text-sm font-bold text-forest">{tr(lang,"Escolha a sua mesa para enviar o pedido.","Choose your table to send the order.")}</div>}
        <div className="space-y-3">{cart.map(line=>{const item=itemMap.get(line.itemId);if(!item)return null;return <div key={line.itemId} className={"rounded-lg border bg-card p-3 "+(invalidItemIds.includes(line.itemId)?"border-destructive/60 bg-destructive/5":"")}><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-semibold">{getLocalized(item.name_pt,item.name_en,lang)}</div><div className="text-sm text-forest">{formatPrice(item.price)}</div></div><div className="flex shrink-0 items-center gap-2"><button onClick={()=>decrement(line.itemId)} aria-label={lang==="pt"?"Diminuir quantidade":"Decrease quantity"} className="flex h-11 w-11 items-center justify-center rounded-full border touch-manipulation active:scale-95"><Minus className="h-4 w-4"/></button><span className="w-7 text-center font-semibold">{line.quantity}</span><button onClick={()=>add(line.itemId)} aria-label={lang==="pt"?"Aumentar quantidade":"Increase quantity"} className="flex h-11 w-11 items-center justify-center rounded-full border touch-manipulation active:scale-95"><Plus className="h-4 w-4"/></button></div></div><>{invalidItemIds.includes(line.itemId)&&<div className="mb-2 rounded px-2 py-1 text-xs font-semibold text-destructive">{tr(lang,"Este item já não está disponível. Remova-o do pedido.","This item is no longer available. Remove it from the order.")}</div>}<input value={line.note} onChange={e=>updateNote(line.itemId,e.target.value)} maxLength={120} placeholder={tr(lang,"Nota para este item (opcional)","Note for this item (optional)")} className="mt-2 w-full rounded border bg-background px-3 py-2 text-sm"/></></div>})}</div>
        <div className="mt-5 grid gap-3"><label className="text-sm font-medium">{tr(lang,"Mesa","Table")}<select value={table} onChange={e=>{setTable(e.target.value);setTableError(false);try{sessionStorage.setItem("vdp-table-number",e.target.value)}catch{}}} className="mt-1 w-full rounded border bg-background px-3 py-2"><option value="">{tr(lang,"Escolher mesa","Choose table")}</option>{(tables.data||[]).map(t=><option key={t.id} value={t.number}>{t.label?t.number+" — "+t.label:"Mesa "+t.number}</option>)}</select></label><label className="text-sm font-medium">{tr(lang,"Nome (opcional)","Name (optional)")}<input value={customer} onChange={e=>setCustomer(e.target.value.slice(0,40))} maxLength={40} className="mt-1 w-full rounded border bg-background px-3 py-2"/></label><label className="text-sm font-medium">{tr(lang,"Observações (opcional)","Notes (optional)")}<textarea value={customerNote} onChange={e=>setCustomerNote(e.target.value.slice(0,200))} maxLength={200} className="mt-1 min-h-20 w-full rounded border bg-background px-3 py-2"/></label><input name="website" value={honeypot} onChange={e=>setHoneypot(e.target.value)} tabIndex={-1} autoComplete="off" aria-hidden="true" className="order-honeypot"/></div>
      </div>
      <footer className="order-modal-footer shrink-0 border-t border-gold/30 bg-cream px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3"><div className="flex items-center justify-between text-lg font-bold"><span>Total</span><span className="text-forest">{formatPrice(total)}</span></div><button disabled={!orderingEnabled||sending||!cart.length} onClick={submit} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-forest px-4 py-3 font-semibold text-cream disabled:opacity-50 touch-manipulation active:scale-[.98]">{sending?<><span className="order-spinner h-5 w-5 rounded-full border-2 border-cream/40 border-t-cream"/> {tr(lang,"A enviar…","Sending…")}</>:tr(lang,"Enviar pedido","Send order")}</button></footer>
    </div></div>,document.body)}  </Ctx.Provider>;
}