/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as QrRouteImport } from './routes/qr'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminDefinicoesRouteImport } from './routes/admin/definicoes'
import { Route as AdminItensRouteImport } from './routes/admin/itens'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMesasRouteImport } from './routes/admin/mesas'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin/utilizadores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDefinicoesRoute = AdminDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItensRoute = AdminItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMesasRoute = AdminMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUtilizadoresRoute = AdminUtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/qr': typeof QrRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/itens': typeof AdminItensRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr': typeof QrRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/itens': typeof AdminItensRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/qr': typeof QrRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/itens': typeof AdminItensRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/utilizadores': typeof AdminUtilizadoresRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/qr'
    | '/admin/categorias'
    | '/admin/definicoes'
    | '/admin/itens'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/setup'
    | '/admin/utilizadores'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/qr'
    | '/admin/categorias'
    | '/admin/definicoes'
    | '/admin/itens'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/setup'
    | '/admin/utilizadores'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/qr'
    | '/admin/categorias'
    | '/admin/definicoes'
    | '/admin/itens'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pedidos'
    | '/admin/setup'
    | '/admin/utilizadores'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  QrRoute: typeof QrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/definicoes': {
      id: '/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AdminDefinicoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/itens': {
      id: '/admin/itens'
      path: '/itens'
      fullPath: '/admin/itens'
      preLoaderRoute: typeof AdminItensRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mesas': {
      id: '/admin/mesas'
      path: '/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AdminMesasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/utilizadores': {
      id: '/admin/utilizadores'
      path: '/utilizadores'
      fullPath: '/admin/utilizadores'
      preLoaderRoute: typeof AdminUtilizadoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminDefinicoesRoute: typeof AdminDefinicoesRoute
  AdminItensRoute: typeof AdminItensRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMesasRoute: typeof AdminMesasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminUtilizadoresRoute: typeof AdminUtilizadoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminDefinicoesRoute: AdminDefinicoesRoute,
  AdminItensRoute: AdminItensRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMesasRoute: AdminMesasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminUtilizadoresRoute: AdminUtilizadoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  QrRoute: QrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
