/* eslint-disable */

// @ts-nocheck

// Generated route tree for Villa das Palmeiras. Regenerated by TanStack Router on build/dev.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrRouteImport } from './routes/qr'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminItensRouteImport } from './routes/admin/itens'
import { Route as AdminDefinicoesRouteImport } from './routes/admin/definicoes'
import { Route as AdminUtilizadoresRouteImport } from './routes/admin/utilizadores'

const IndexRoute=IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const QrRoute=QrRouteImport.update({id:'/qr',path:'/qr',getParentRoute:()=>rootRouteImport} as any)
const AdminRoute=AdminRouteImport.update({id:'/admin',path:'/admin',getParentRoute:()=>rootRouteImport} as any)
const AdminIndexRoute=AdminIndexRouteImport.update({id:'/admin/',path:'/',getParentRoute:()=>AdminRoute} as any)
const AdminLoginRoute=AdminLoginRouteImport.update({id:'/admin/login',path:'/login',getParentRoute:()=>AdminRoute} as any)
const AdminSetupRoute=AdminSetupRouteImport.update({id:'/admin/setup',path:'/setup',getParentRoute:()=>AdminRoute} as any)
const AdminCategoriasRoute=AdminCategoriasRouteImport.update({id:'/admin/categorias',path:'/categorias',getParentRoute:()=>AdminRoute} as any)
const AdminItensRoute=AdminItensRouteImport.update({id:'/admin/itens',path:'/itens',getParentRoute:()=>AdminRoute} as any)
const AdminDefinicoesRoute=AdminDefinicoesRouteImport.update({id:'/admin/definicoes',path:'/definicoes',getParentRoute:()=>AdminRoute} as any)
const AdminUtilizadoresRoute=AdminUtilizadoresRouteImport.update({id:'/admin/utilizadores',path:'/utilizadores',getParentRoute:()=>AdminRoute} as any)

export interface FileRoutesByFullPath {
  '/':typeof IndexRoute
  '/qr':typeof QrRoute
  '/admin/':typeof AdminIndexRoute
  '/admin/login':typeof AdminLoginRoute
  '/admin/setup':typeof AdminSetupRoute
  '/admin/categorias':typeof AdminCategoriasRoute
  '/admin/itens':typeof AdminItensRoute
  '/admin/definicoes':typeof AdminDefinicoesRoute
  '/admin/utilizadores':typeof AdminUtilizadoresRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__:typeof rootRouteImport
  '/':typeof IndexRoute
  '/qr':typeof QrRoute
  '/admin':typeof AdminRoute
  '/admin/':typeof AdminIndexRoute
  '/admin/login':typeof AdminLoginRoute
  '/admin/setup':typeof AdminSetupRoute
  '/admin/categorias':typeof AdminCategoriasRoute
  '/admin/itens':typeof AdminItensRoute
  '/admin/definicoes':typeof AdminDefinicoesRoute
  '/admin/utilizadores':typeof AdminUtilizadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath:FileRoutesByFullPath
  fullPaths:'/'|'/qr'|'/admin/'|'/admin/login'|'/admin/setup'|'/admin/categorias'|'/admin/itens'|'/admin/definicoes'|'/admin/utilizadores'
  fileRoutesByTo:FileRoutesByTo
  to:FileRoutesByFullPath[keyof FileRoutesByFullPath] extends never ? never : keyof FileRoutesByFullPath
  id:keyof FileRoutesById
  fileRoutesById:FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute:typeof IndexRoute
  QrRoute:typeof QrRoute
  AdminRoute:typeof AdminRoute
}
export interface AdminRouteChildren {
  AdminIndexRoute:typeof AdminIndexRoute
  AdminLoginRoute:typeof AdminLoginRoute
  AdminSetupRoute:typeof AdminSetupRoute
  AdminCategoriasRoute:typeof AdminCategoriasRoute
  AdminItensRoute:typeof AdminItensRoute
  AdminDefinicoesRoute:typeof AdminDefinicoesRoute
  AdminUtilizadoresRoute:typeof AdminUtilizadoresRoute
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport}
    '/qr':{id:'/qr';path:'/qr';fullPath:'/qr';preLoaderRoute:typeof QrRouteImport;parentRoute:typeof rootRouteImport}
    '/admin':{id:'/admin';path:'/admin';fullPath:'/admin';preLoaderRoute:typeof AdminRouteImport;parentRoute:typeof rootRouteImport}
    '/admin/':{id:'/admin/';path:'/';fullPath:'/admin/';preLoaderRoute:typeof AdminIndexRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/login':{id:'/admin/login';path:'/login';fullPath:'/admin/login';preLoaderRoute:typeof AdminLoginRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/setup':{id:'/admin/setup';path:'/setup';fullPath:'/admin/setup';preLoaderRoute:typeof AdminSetupRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/categorias':{id:'/admin/categorias';path:'/categorias';fullPath:'/admin/categorias';preLoaderRoute:typeof AdminCategoriasRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/itens':{id:'/admin/itens';path:'/itens';fullPath:'/admin/itens';preLoaderRoute:typeof AdminItensRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/definicoes':{id:'/admin/definicoes';path:'/definicoes';fullPath:'/admin/definicoes';preLoaderRoute:typeof AdminDefinicoesRouteImport;parentRoute:typeof AdminRouteImport}
    '/admin/utilizadores':{id:'/admin/utilizadores';path:'/utilizadores';fullPath:'/admin/utilizadores';preLoaderRoute:typeof AdminUtilizadoresRouteImport;parentRoute:typeof AdminRouteImport}
  }
}
const adminRouteChildren:AdminRouteChildren={AdminIndexRoute,AdminLoginRoute,AdminSetupRoute,AdminCategoriasRoute,AdminItensRoute,AdminDefinicoesRoute,AdminUtilizadoresRoute}
const rootRouteChildren:RootRouteChildren={IndexRoute,QrRoute,AdminRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
AdminRoute._addFileChildren(adminRouteChildren)

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr:true
    router:Awaited<ReturnType<typeof getRouter>>
    config:Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
